const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{鼠标: 0},
	{音频: 0},
	{开场主标题: 0},
	{开场副标题: 0},
	{开始探索: 0},
	{通用提示文字: 0},
	{倒座房文本: 0},
	{兰门簪: 0},
	{梅门簪: 0},
	{竹门簪: 0},
	{淡入淡出: 0},
	{开头: 0},
	{触控: 0},
	{密码提示: 0},
	{错误提示: 0},
	{东厢房了解: 0},
	{进入内院: 0},
	{精灵4: 0},
	{精灵7: 0},
	{精灵10: 0},
	{箭头: 0},
	{按钮门1: 0},
	{精灵12: 0},
	{精灵13: 0},
	{东厢房: 0},
	{西厢房: 0},
	{西厢房了解: 0},
	{倒座房了解: 0},
	{垂花门: 0},
	{精灵14: 0},
	{精灵15: 0},
	{精灵17: 0},
	{榫卯: 0},
	{精灵18: 0},
	{垂花房: 0},
	{榫卯按钮: 0},
	{榫卯结构: 0},
	{后院介绍文本: 0},
	{内院进入: 0},
	{探索结束: 0},
	{正房: 0},
	{进入后院: 0},
	{音乐: 0},
	{正房介绍: 0},
	{正房介绍文本: 0},
	{密码1: 0},
	{密码2: 0},
	{密码3: 0},
	{密码4: 0},
	{密码5: 0},
	{梅花簪: 0},
	{切换次数: 0},
	{文本: 0},
	{垂花: 0},
	{Istextshow: 0},
	{Istextshow2: 0},
	{Istextshow3: 0}
];

self.InstanceType = {
	鼠标: class extends self.IInstance {},
	音频: class extends self.IInstance {},
	开场主标题: class extends self.ITextInstance {},
	开场副标题: class extends self.ITextInstance {},
	开始探索: class extends self.IButtonInstance {},
	通用提示文字: class extends self.ITextInstance {},
	倒座房文本: class extends self.ITextInstance {},
	兰门簪: class extends self.ISpriteInstance {},
	梅门簪: class extends self.ISpriteInstance {},
	竹门簪: class extends self.ISpriteInstance {},
	开头: class extends self.ISpriteInstance {},
	触控: class extends self.IInstance {},
	密码提示: class extends self.ITextInstance {},
	错误提示: class extends self.ITextInstance {},
	东厢房了解: class extends self.ITextInstance {},
	进入内院: class extends self.IButtonInstance {},
	精灵4: class extends self.ISpriteInstance {},
	精灵7: class extends self.ISpriteInstance {},
	精灵10: class extends self.ISpriteInstance {},
	箭头: class extends self.ISpriteInstance {},
	按钮门1: class extends self.IButtonInstance {},
	精灵12: class extends self.ISpriteInstance {},
	精灵13: class extends self.ISpriteInstance {},
	东厢房: class extends self.IButtonInstance {},
	西厢房: class extends self.IButtonInstance {},
	西厢房了解: class extends self.ITextInstance {},
	倒座房了解: class extends self.IButtonInstance {},
	垂花门: class extends self.IButtonInstance {},
	精灵14: class extends self.ISpriteInstance {},
	精灵15: class extends self.ISpriteInstance {},
	精灵17: class extends self.ISpriteInstance {},
	榫卯: class extends self.ISpriteInstance {},
	精灵18: class extends self.ISpriteInstance {},
	垂花房: class extends self.ITextInstance {},
	榫卯按钮: class extends self.IButtonInstance {},
	榫卯结构: class extends self.ITextInstance {},
	后院介绍文本: class extends self.ITextInstance {},
	内院进入: class extends self.IButtonInstance {},
	探索结束: class extends self.IButtonInstance {},
	正房: class extends self.IButtonInstance {},
	进入后院: class extends self.IButtonInstance {},
	音乐: class extends self.IButtonInstance {},
	正房介绍: class extends self.IButtonInstance {},
	正房介绍文本: class extends self.ITextInstance {},
	密码1: class extends self.IButtonInstance {},
	密码2: class extends self.IButtonInstance {},
	密码3: class extends self.IButtonInstance {},
	密码4: class extends self.IButtonInstance {},
	密码5: class extends self.IButtonInstance {}
}